version: "3.7"

services:
  srv-nginx:
    build: nginx
    image: nginx:0.1
    environment:
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
    container_name: nginx
    networks:
      - net-inception
    volumes:
      - vol-wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      srv-wordpress:
        condition: service_healthy
    restart: always
 
  srv-wordpress:
    build: wordpress
    image: wordpress:0.1
    environment:
      DATABASE_DBNAME: ${MARIADB_WORDPRESS_DBNAME}
      DATABASE_USERNAME: ${MARIADB_WORDPRESS_USERNAME}
      DATABASE_PASSWORD: ${MARIADB_WORDPRESS_PASSWORD}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      ADMIN_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      USER_USERNAME: ${WORDPRESS_USER_USERNAME}
      USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      USER_EMAIL: ${WORDPRESS_USER_EMAIL}
    container_name: wordpress
    networks:
      - net-inception
    volumes:
      - vol-wordpress:/var/www/wordpress
    depends_on:
      srv-mariadb:
        condition: service_healthy
    restart: always

  srv-mariadb:
    build: mariadb
    image: mariadb:0.1
    environment:
      ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DBNAME: ${MARIADB_WORDPRESS_DBNAME}
      WORDPRESS_USERNAME: ${MARIADB_WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${MARIADB_WORDPRESS_PASSWORD}
    container_name: mariadb
    networks:
      - net-inception
    volumes:
      - vol-mariadb:/var/lib/mysql
    restart: always

volumes:
  vol-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sangkkim/data/wordpress
    name: wordpress
  
  vol-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sangkkim/data/mariadb
    name: mariadb

networks:
  net-inception:
    driver: bridge
    name: inception
