version: "3.7"

services:
  srv-nginx:
    depends_on:
      srv-wordpress:
        condition: service_healthy
    build:
      context: nginx
      args:
        DOCKER_BUILDKIT: 1
    image: nginx:0.1
    container_name: nginx
    networks:
      - net-inception
    volumes:
      - vol-wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
 
  srv-wordpress:
    depends_on:
      srv-mariadb:
        condition: service_healthy
    build:
      context: wordpress
      args:
        DOCKER_BUILDKIT: 1
    image: wordpress:0.1
    container_name: wordpress
    networks:
      - net-inception
    volumes:
      - vol-wordpress:/var/www/wordpress
    restart: always
    environment:
      DATABASE_DBNAME: ${MARIADB_WORDPRESS_DBNAME}
      DATABASE_USERNAME: ${MARIADB_WORDPRESS_USERNAME}
      DATABASE_PASSWORD: ${MARIADB_WORDPRESS_PASSWORD}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      ADMIN_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
  
  srv-mariadb:
    build:
      context: mariadb
      args:
        DOCKER_BUILDKIT: 1
    image: mariadb:0.1
    container_name: mariadb
    networks:
      - net-inception
    volumes:
      - vol-mariadb:/var/lib/mysql
    restart: always
    environment:
      WORDPRESS_DBNAME: ${MARIADB_WORDPRESS_DBNAME}
      WORDPRESS_USERNAME: ${MARIADB_WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${MARIADB_WORDPRESS_PASSWORD}

volumes:
  vol-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sangkkim/data/wordpress
    name: wordpress
  
  vol-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sangkkim/data/mariadb
    name: mariadb

networks:
  net-inception:
    driver: bridge
    name: inception
